on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Clone Repo
        run: |
          git clone https://github.com/OpenHFT/Chronicle-Wire
      - name: Compile test module and dependencies
        run: | 
          cd Chronicle-Wire
          mvn test-compile -q --file pom.xml -am
      - name: Run test
        run: |
          cd Chronicle-Wire
          mvn --file pom.xml test -Dtest=net.openhft.chronicle.wire.TextWireTest#testABCDBytes
      - name: Run test with NonDex tool
        run: |
          cd Chronicle-Wire
          mvn --file pom.xml edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=net.openhft.chronicle.wire.TextWireTest#testABCDBytes -DnondexRuns=10